apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: labelgun
spec:
  template:
    metadata:
      labels:
        app: labelgun
      name: labelgun
    spec:
      containers:
      - image: geota/labelgun
        imagePullPolicy: Always
        name: labelgun
        env:
          - name: AWS_REGION
            value: "us-west-2"
          - name: LABELGUN_INTERVAL
            value: "360"
          - name: LABELGUN_SUPPRESS_LOG
            value: "false"
          - name: LABELGUN_NO_SCHEDULE_TAG_PREFIX
            value: "rmn.io/no-schedule"
          - name: LABELGUN_PREFER_NO_SCHEDULE_TAG_PREFIX
            value: "rmn.io/prefer-no-schedule"
          - name: LABELGUN_NO_EXECUTE_TAG_PREFIX
            value: "rmn.io/no-execute"
