---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: labelgun
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: labelgun
    spec:
      containers:
        -
          env:
            -
              name: AWS_REGION
              value: us-west-2
            -
              name: LABELGUN_ERR_THRESHOLD
              value: INFO
            -
              name: LABELGUN_INTERVAL
              value: "360"
            -
              name: LABELGUN_SUPPRESS_LOG
              value: "false"
            -
              name: LABELGUN_LABEL_TAG_PREFIX
              value: rmn.io/
            -
              name: LABELGUN_NO_SCHEDULE_TAG_PREFIX
              value: rmn.io/no-schedule
            -
              name: LABELGUN_PREFER_NO_SCHEDULE_TAG_PREFIX
              value: rmn.io/prefer-no-schedule
            -
              name: LABELGUN_NO_EXECUTE_TAG_PREFIX
              value: rmn.io/no-execute
          image: "geota/labelgun:latest"
          imagePullPolicy: Always
          name: labelgun
